const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("🚀 Deploying AvatarNFT contract...");

  // Get the contract factory
  const AvatarNFT = await hre.ethers.getContractFactory("AvatarNFT");
  
  // Deploy the contract
  const avatarNFT = await AvatarNFT.deploy();
  
  await avatarNFT.waitForDeployment();
  const address = await avatarNFT.getAddress();

  console.log("✅ AvatarNFT deployed to:", address);
  console.log("📝 Contract address:", address);
  console.log("\n🔍 Verify contract:");
  console.log(`npx hardhat verify --network baseSepolia ${address}`);

  // Read ABI from artifact file
  const artifactPath = path.join(
    __dirname,
    "../artifacts/contracts/AvatarNFT.sol/AvatarNFT.json"
  );
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  const abi = artifact.abi;

  // Path to contract-address.js: from scripts/ to src/
  // scripts/ -> contracts/ -> avatar-system/ -> src/
  const contractAddressPath = path.join(__dirname, "../../src/contract-address.js");

  // Generate contract-address.js file with address and ABI
  const contractAddressContent = `// Auto-generated contract address and ABI
// Generated at: ${new Date().toISOString()}
// DO NOT EDIT MANUALLY - This file is auto-generated by deploy script

export const CONTRACT_ADDRESS = "${address}";
export const CONTRACT_NETWORK = "baseSepolia";
export const CONTRACT_CHAIN_ID = 84532;

// Contract ABI for frontend interaction
export const CONTRACT_ABI = ${JSON.stringify(abi, null, 2)};
`;

  // Write to file
  fs.writeFileSync(contractAddressPath, contractAddressContent);
  
  console.log("\n✅ Contract address and ABI saved to: avatar-system/src/contract-address.js");
  console.log(`📦 ABI contains ${abi.length} items (functions, events, errors)`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });

